---
- name: install apache 
  yum: name=httpd state=present 
  ignore_errors: yes

#- name: copy apache template
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf 

- name: config apache to excute php
  lineinfile: dest=/etc/httpd/conf/httpd.conf state=present create=yes regexp="^AddType"  insertafter="^AddType application/x-gzip .gz .tgz" 
              line="AddType application/x-httpd-php .php"
  notify: restart apache

- name: add rule to iptables
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ apache_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ apache_port }} -j  ACCEPT"
  notify: restart iptables

- name: start apache and permanent
  service: name=httpd state=restarted enabled=yes
  ignore_errors: yes

