---
- name: install apache 
  yum: name=httpd state=present 
  ignore_errors: yes

#- name: copy apache template
#  template: src=default.conf dest=/etc/nginx/conf.d/default.conf 

- name: start firewalld
  service: name=firewalld state=started enabled=yes

- name: instert firewalld rule for apache
  firewalld: port={{ apache_port }}/tcp  permanent=true state=enabled immediate=yes
  ignore_errors: yes  

- name: start apache and permanent
  service: name=httpd state=restarted enabled=yes
  ignore_errors: yes


