---
- name: Install libselinux-python and libsemanage-python
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - firewalld
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  ignore_errors: yes

- name: Install libselinux-python and libsemanage-python
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  ignore_errors: yes